services:
  - type: web
    name: seedbox-backend
    env: docker
    dockerfilePath: ./server/Dockerfile
    buildCommand: docker build -t seedbox-backend ./server
    startCommand: docker run -p 3001:3001 seedbox-backend
    plan: starter
    envVars:
      - key: BACKEND_PORT
        value: "3001"
    mounts:
      - type: volume
        name: seedbox_data
        mountPath: /app/data
      - type: volume
        name: seedbox_cache
        mountPath: /app/cache

  - type: web
    name: seedbox-frontend
    env: docker
    dockerfilePath: ./client/Dockerfile
    buildCommand: docker build --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL -t seedbox-frontend ./client
    startCommand: docker run -p 5174:80 seedbox-frontend
    plan: starter
    envVars:
      - key: VITE_API_BASE_URL
        value: "http://seedbox-backend:3001"
    dependsOn:
      - seedbox-backend

volumes:
  - name: seedbox_data
  - name: seedbox_cache
